export * from './store'
export { searchMoviesByPopular } from './action-creators/searchMoviesByPopularActionCreator'
export { searchMoviesByTopRated } from './action-creators/searchMoviesByTopRatedActionCreator'
export { searchMoviesByUpComing } from './action-creators/searchMoviesByUpComingActionCreator'
export * from './reducers'
export * as state from './moviesState'